"""
Infrastructure-JEPA: Critical Network Node Localisation
========================================================
Domain-agnostic validation of the Topological Vulnerability Targeting Engine
(Latent Fault Locator) applied to the network infrastructure domain.

Domain Isomorphism
------------------
The identical mathematical pipeline routes three structurally equivalent
problems without any modification to the Lár execution spine:

  Materials domain    : thermodynamic entropy states × crystal lattice sites
                        → topk critical physical instability coordinates
  Seismic domain      : crustal stress field × geological fault topology
                        → topk seismic risk coordinates
  Infrastructure domain: network traffic load × server graph topology
                         → topk critical failure nodes              ← this file

The cross-attention operator projects continuous environmental-state tensors
(Query: live network traffic observations) against structural-sequence tensors
(Key/Value: server graph topology) to extract the topk nodes whose failure
would most critically degrade the network — the "Latent Fault Locator" applied
to distributed systems.

This is precisely the same mathematical operation as:
  Drug Discovery  : RNA disease state queries DNA structural positions
  Crystal Physics : Electrochemical state queries crystal lattice sites
  Geophysics      : Crustal stress field queries geological fault segments

Data sourcing (production)
--------------------------
Traffic observations : SNMP/IPFIX telemetry streams (Prometheus, Grafana Mimir)
Network topology     : BGP route reflector graph exports, LLDP neighbour tables
                       CAIDA AS-Rank dataset (public domain)
                       SNAP Stanford Network Dataset Collection (public domain)
Checkpoint weights   : Trained on public Internet topology datasets; no
                       proprietary infrastructure data used.

This PoC uses synthetic tensors with realistic shapes and domain semantics
generated by torch.rand. No proprietary, commercial, or governmental network
data is used or required. The architecture, graph topology, and execution
spine are production-grade.

Graph topology
--------------

  NetworkLoadEmbeddingNode    (encode traffic observations → Z_load)
           ↓
  TopologyGraphEmbeddingNode  (encode server graph structure → Z_topo)
           ↓
  CriticalNodeHeadNode        (cross-attention Z_load × Z_topo → risk, topk nodes)
           ↓
  FailureRiskRouterNode       (route on criticality tier)
     ├── CRITICAL → IncidentReportNode  → Done
     └── NOMINAL  → MonitorLogNode     → Done

Run
---
    cd lar_jepa
    python examples/infrastructure_jepa_showcase.py
"""

import sys
import os
import math
import torch
import torch.nn as nn

# ---------------------------------------------------------------------------
# Path bootstrap
# ---------------------------------------------------------------------------
_ROOT      = os.path.dirname(os.path.abspath(__file__))
_JEPA_ROOT = os.path.abspath(os.path.join(_ROOT, ".."))
_LAR_SRC   = os.path.join(_JEPA_ROOT, "lar_jepa", "src")

for _p in [_JEPA_ROOT, _LAR_SRC]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from lar import GraphState, GraphExecutor, BaseNode

# ---------------------------------------------------------------------------
# Domain constants — network monitoring
# ---------------------------------------------------------------------------
# Monitoring probes distributed across network ingress/egress points.
# Each probe records per-link telemetry aggregated into a feature vector.
N_PROBES    = 24    # network monitoring probes (environmental state nodes)
LOAD_DIM    = 64    # latent network load embedding dimension

# Server / router nodes in the target autonomous system.
# Each node encodes: degree centrality, betweenness, eigenvector centrality,
# current load score, uptime ratio, interface saturation index.
N_NODES     = 40    # network infrastructure nodes (structural topology nodes)
TOPOLOGY_DIM = 64   # latent topology embedding dimension

# Node labels — representative data-centre / backbone topology
NODE_LABELS = [
    "Core Router — Primary",              "Core Router — Secondary",
    "Spine Switch — Rack A",              "Spine Switch — Rack B",
    "Spine Switch — Rack C",              "Spine Switch — Rack D",
    "Leaf Switch — Zone 1",               "Leaf Switch — Zone 2",
    "Leaf Switch — Zone 3",               "Leaf Switch — Zone 4",
    "Border Gateway — AS Peering 1",      "Border Gateway — AS Peering 2",
    "Load Balancer — Tier 1",             "Load Balancer — Tier 2",
    "Firewall Cluster — North",           "Firewall Cluster — South",
    "Database Primary — Shard A",         "Database Replica — Shard A",
    "Database Primary — Shard B",         "Database Replica — Shard B",
    "API Gateway — Region West",          "API Gateway — Region East",
    "CDN Edge — PoP Alpha",               "CDN Edge — PoP Beta",
    "DNS Authoritative — Primary",        "DNS Authoritative — Secondary",
    "MPLS Hub — Transit Node",            "MPLS Hub — Edge Node",
    "IXP Peering — Carrier 1",            "IXP Peering — Carrier 2",
    "Service Mesh — Control Plane",       "Service Mesh — Data Plane",
    "Monitoring Aggregator — Primary",    "Monitoring Aggregator — Secondary",
    "Object Storage — Primary",           "Object Storage — Replica",
    "Cache Cluster — L1",                 "Cache Cluster — L2",
    "Message Broker — Leader",            "Message Broker — Follower",
]


def get_mock_network_input(n_snapshots: int = 4):
    """
    Generate synthetic network telemetry snapshots.

    Returns
    -------
    load_data     : (n_snapshots, N_PROBES, 6)
        Per-probe feature vectors:
        [throughput_norm, latency_ms_norm, packet_loss_pct,
         jitter_norm, probe_cpu_util, link_saturation]
    topo_data     : (1, N_NODES, 6)
        Per-node structural parameters:
        [in_degree_norm, out_degree_norm, betweenness_centrality,
         eigenvector_centrality, load_score, uptime_ratio]

    In production, load_data is derived from SNMP/IPFIX streams and
    topo_data from BGP route-reflector exports or LLDP neighbour tables.
    """
    torch.manual_seed(13)
    load_data = torch.rand(n_snapshots, N_PROBES, 6)
    topo_data = torch.rand(1, N_NODES, 6)
    return load_data, topo_data


# ---------------------------------------------------------------------------
# NetworkLoadJEPA — encodes live traffic observations into latent load state
# ---------------------------------------------------------------------------

class NetworkLoadJEPA(nn.Module):
    """
    JEPA encoder for the network traffic load field (environmental state).

    Input  : (B, N_PROBES, 6) — per-probe telemetry feature vectors
    Output : (B, LOAD_DIM)    — mean-pooled latent load embedding

    The encoder learns which combinations of probe observations (throughput,
    latency, packet loss) are predictive of the underlying network stress
    state — the "world model" representation of current traffic conditions.
    Pooled to a single vector: this is the Query in the cross-attention.
    """
    def __init__(self, in_features: int = 6, embed_dim: int = LOAD_DIM):
        super().__init__()
        self.probe_encoder = nn.Sequential(
            nn.Linear(in_features, 128),
            nn.LayerNorm(128),
            nn.GELU(),
            nn.Linear(128, embed_dim),
        )
        self.probe_attention = nn.MultiheadAttention(
            embed_dim=embed_dim, num_heads=4, batch_first=True
        )
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.probe_encoder(x)               # (B, N_PROBES, LOAD_DIM)
        z_attn, _ = self.probe_attention(z, z, z)
        return self.norm(z + z_attn)            # (B, N_PROBES, LOAD_DIM)

    def encode_load_state(self, x: torch.Tensor) -> torch.Tensor:
        """Returns mean-pooled load embedding: (B, LOAD_DIM)."""
        probe_embs = self.forward(x)            # (B, N_PROBES, LOAD_DIM)
        return probe_embs.mean(dim=1)           # (B, LOAD_DIM)


# ---------------------------------------------------------------------------
# TopologyGraphJEPA — encodes server graph topology into structural sequence
# ---------------------------------------------------------------------------

class TopologyGraphJEPA(nn.Module):
    """
    JEPA encoder for the network graph topology (structural state).

    Input  : (1, N_NODES, 6)          — per-node centrality / load parameters
    Output : (1, N_NODES, TOPOLOGY_DIM) — per-node latent topology embeddings

    The encoder learns which structural configurations (high betweenness,
    eigenvector centrality, degree) are associated with failure propagation
    risk — the "world model" representation of the network's vulnerability
    landscape. Kept as a positional sequence: these are the Keys and Values
    in the cross-attention.
    """
    def __init__(self, in_features: int = 6, embed_dim: int = TOPOLOGY_DIM):
        super().__init__()
        self.node_encoder = nn.Sequential(
            nn.Linear(in_features, 128),
            nn.LayerNorm(128),
            nn.GELU(),
            nn.Linear(128, embed_dim),
        )
        self.graph_attention = nn.MultiheadAttention(
            embed_dim=embed_dim, num_heads=4, batch_first=True
        )
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.node_encoder(x)                      # (1, N_NODES, TOPOLOGY_DIM)
        z_attn, _ = self.graph_attention(z, z, z)
        return self.norm(z + z_attn)                  # (1, N_NODES, TOPOLOGY_DIM)


# ---------------------------------------------------------------------------
# CriticalNodeHead — cross-attention: load state × topology → failure risk
# ---------------------------------------------------------------------------

class CriticalNodeHead(nn.Module):
    """
    Cross-attention prediction head for critical node localisation.

    This is the Latent Fault Locator applied to the network infrastructure domain.

    load_state    : (B, LOAD_DIM)         — pooled load embedding (Query)
    topo_nodes    : (1, N_NODES, D)       — per-node topology embeddings (Key, Value)

    The network load state is the Query: given the current traffic and stress
    conditions observed across all monitoring probes, which specific server
    or router nodes are most likely to cause a cascading failure?

    This is mathematically identical to:
      Drug-JEPA     : RNA disease state queries which DNA positions are kill switches
      Materials-JEPA: Electrochemical state queries which crystal sites are unstable
      Seismic-JEPA  : Crustal stress field queries which fault segments carry risk

    Returns
    -------
    failure_prob  : (B, 1)       — probability of cascade failure event [0, 1]
    attn_weights  : (B, N_NODES) — per-node attention weights (criticality scores)
    """
    def __init__(self, embed_dim: int = LOAD_DIM):
        super().__init__()
        self.query_proj = nn.Linear(embed_dim, embed_dim)
        self.key_proj   = nn.Linear(embed_dim, embed_dim)
        self.value_proj = nn.Linear(embed_dim, embed_dim)
        self.failure_head = nn.Sequential(
            nn.Linear(embed_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid(),
        )
        self.embed_dim = embed_dim

    def forward(
        self,
        load_state : torch.Tensor,   # (B, D)
        topo_nodes : torch.Tensor,   # (1, N_NODES, D)
    ):
        B = load_state.shape[0]
        topo_exp = topo_nodes.expand(B, -1, -1)          # (B, N_NODES, D)

        Q = self.query_proj(load_state).unsqueeze(1)     # (B, 1, D)
        K = self.key_proj(topo_exp)                      # (B, N_NODES, D)
        V = self.value_proj(topo_exp)                    # (B, N_NODES, D)

        scores = torch.bmm(Q, K.transpose(1, 2)) / math.sqrt(self.embed_dim)
        attn   = torch.softmax(scores, dim=-1)           # (B, 1, N_NODES)
        ctx    = torch.bmm(attn, V).squeeze(1)           # (B, D)

        failure_prob = self.failure_head(ctx)            # (B, 1)
        attn_weights = attn.squeeze(1)                   # (B, N_NODES)
        return failure_prob, attn_weights

    def topk_critical_nodes(
        self,
        attn_weights: torch.Tensor,
        k: int = 3,
    ) -> list:
        """Return the node labels with the highest attention weight."""
        top_idx = attn_weights.squeeze().topk(k).indices.tolist()
        return [(NODE_LABELS[i], i) for i in top_idx]


# ---------------------------------------------------------------------------
# Instantiate models (CPU, no pre-trained weights needed for validation)
# ---------------------------------------------------------------------------
_load_jepa  = NetworkLoadJEPA()
_topo_jepa  = TopologyGraphJEPA()
_crit_head  = CriticalNodeHead()

_load_jepa.eval()
_topo_jepa.eval()
_crit_head.eval()


# ---------------------------------------------------------------------------
# Lár Graph Nodes
# ---------------------------------------------------------------------------

class NetworkLoadEmbeddingNode(BaseNode):
    """
    Encodes raw per-probe traffic telemetry into the latent load state.

    Reads  : state["load_data"]          (B, N_PROBES, 6)
    Writes : state["load_embedding"]     (B, LOAD_DIM)
             state["snapshot_index"]     int
    """
    def __init__(self, jepa: NetworkLoadJEPA, next_node=None):
        self.jepa      = jepa
        self.next_node = next_node

    def execute(self, state: GraphState):
        load_data = state.get("load_data")       # (B, N_PROBES, 6)
        with torch.no_grad():
            z_load = self.jepa.encode_load_state(load_data)   # (B, LOAD_DIM)

        state.set("load_embedding", z_load)
        idx = state.get("snapshot_index", 0)
        print(f"\n[NetworkLoadEmbeddingNode] Snapshot {idx}: "
              f"load state encoded → Z_load shape {list(z_load.shape)}, "
              f"mean={z_load.mean().item():.4f}")
        return self.next_node


class TopologyGraphEmbeddingNode(BaseNode):
    """
    Encodes the network graph topology into the structural node sequence.

    Reads  : state["topo_data"]          (1, N_NODES, 6)
    Writes : state["topo_embedding"]     (1, N_NODES, TOPOLOGY_DIM)
    """
    def __init__(self, jepa: TopologyGraphJEPA, next_node=None):
        self.jepa      = jepa
        self.next_node = next_node

    def execute(self, state: GraphState):
        topo_data = state.get("topo_data")       # (1, N_NODES, 6)
        with torch.no_grad():
            z_topo = self.jepa(topo_data)        # (1, N_NODES, TOPOLOGY_DIM)

        state.set("topo_embedding", z_topo)
        print(f"\n[TopologyGraphEmbeddingNode] Graph topology encoded → "
              f"Z_topo shape {list(z_topo.shape)}, "
              f"mean={z_topo.mean().item():.4f}")
        return self.next_node


class CriticalNodeHeadNode(BaseNode):
    """
    Applies cross-attention to project the network load state against the
    infrastructure topology, identifying the topk critical failure nodes.

    Reads  : state["load_embedding"]     (B, LOAD_DIM)
             state["topo_embedding"]     (1, N_NODES, TOPOLOGY_DIM)
    Writes : state["failure_prob"]       float in [0, 1]
             state["critical_nodes"]     list of (label, node_index) tuples
             state["attn_weights"]       (B, N_NODES)
    """
    def __init__(self, head: CriticalNodeHead, k: int = 3, next_node=None):
        self.head      = head
        self.k         = k
        self.next_node = next_node

    def execute(self, state: GraphState):
        z_load = state.get("load_embedding")     # (B, LOAD_DIM)
        z_topo = state.get("topo_embedding")     # (1, N_NODES, TOPOLOGY_DIM)

        with torch.no_grad():
            failure_prob, attn_weights = self.head(z_load, z_topo)

        prob_val       = failure_prob.mean().item()
        critical_nodes = self.head.topk_critical_nodes(attn_weights, k=self.k)

        state.set("failure_prob",    prob_val)
        state.set("critical_nodes",  critical_nodes)
        state.set("attn_weights",    attn_weights)

        print(f"\n[CriticalNodeHeadNode]  failure probability = {prob_val:.4f}")
        print(f"  topk critical nodes (k={self.k}):")
        for label, idx in critical_nodes:
            w = attn_weights.mean(0)[idx].item()
            print(f"    [{idx:>2}] {label:<45} attn={w:.4f}")
        return self.next_node


class FailureRiskRouterNode(BaseNode):
    """
    Routes on cascade failure probability.

    CRITICAL (prob >= threshold) → critical_node
    NOMINAL                      → nominal_node
    """
    def __init__(
        self,
        threshold: float = 0.50,
        critical_node=None,
        nominal_node=None,
    ):
        self.threshold     = threshold
        self.critical_node = critical_node
        self.nominal_node  = nominal_node

    def execute(self, state: GraphState):
        prob = state.get("failure_prob", 0.0)
        tier = "CRITICAL" if prob >= self.threshold else "NOMINAL"
        state.set("risk_tier", tier)
        print(f"\n[FailureRiskRouterNode]  prob={prob:.4f}  threshold={self.threshold}  → {tier}")
        return self.critical_node if prob >= self.threshold else self.nominal_node


class IncidentReportNode(BaseNode):
    """
    Generates a structured infrastructure incident report and escalation record.
    """
    def __init__(self, next_node=None):
        self.next_node = next_node

    def execute(self, state: GraphState):
        failure_prob   = state.get("failure_prob", 0.0)
        critical_nodes = state.get("critical_nodes", [])
        snapshot_idx   = state.get("snapshot_index", 0)

        report = {
            "snapshot_index":   snapshot_idx,
            "risk_tier":        "CRITICAL",
            "failure_prob":     round(failure_prob, 4),
            "critical_nodes": [
                {"label": label, "node_id": idx}
                for label, idx in critical_nodes
            ],
            "recommendation":   "Escalate to NOC. Initiate failover on identified nodes. "
                                 "Increase monitoring frequency. Review capacity on flagged paths.",
        }
        state.set("incident_report", report)

        print("\n" + "=" * 60)
        print("  INFRASTRUCTURE INCIDENT REPORT — CRITICAL")
        print("=" * 60)
        print(f"  Snapshot:         {snapshot_idx}")
        print(f"  Failure Prob:     {failure_prob:.4f}")
        print(f"  Critical Nodes:")
        for node in report["critical_nodes"]:
            print(f"    • [{node['node_id']:>2}] {node['label']}")
        print(f"  Recommendation:   {report['recommendation']}")
        print("=" * 60)
        return self.next_node


class MonitorLogNode(BaseNode):
    """Logs a nominal-risk telemetry snapshot for background monitoring."""
    def __init__(self, next_node=None):
        self.next_node = next_node

    def execute(self, state: GraphState):
        prob = state.get("failure_prob", 0.0)
        idx  = state.get("snapshot_index", 0)
        print(f"\n[MonitorLogNode] Snapshot {idx}: prob={prob:.4f} — nominal. Logged for trending.")
        state.set("incident_report", {"snapshot_index": idx, "risk_tier": "NOMINAL", "failure_prob": round(prob, 4)})
        return self.next_node


# ---------------------------------------------------------------------------
# Graph Assembly
# ---------------------------------------------------------------------------

def build_infrastructure_graph():
    """
    Assembles and returns the Lár infrastructure risk graph.
    """
    incident_node = IncidentReportNode(next_node=None)
    monitor_node  = MonitorLogNode(next_node=None)

    router_node = FailureRiskRouterNode(
        threshold=0.50,
        critical_node=incident_node,
        nominal_node=monitor_node,
    )

    crit_head_node = CriticalNodeHeadNode(
        head=_crit_head,
        k=3,
        next_node=router_node,
    )

    topo_emb_node = TopologyGraphEmbeddingNode(
        jepa=_topo_jepa,
        next_node=crit_head_node,
    )

    load_emb_node = NetworkLoadEmbeddingNode(
        jepa=_load_jepa,
        next_node=topo_emb_node,
    )

    return load_emb_node   # entry point


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("\n" + "=" * 60)
    print("  Infrastructure-JEPA: Critical Node Localisation")
    print("  Latent Fault Locator — Network Infrastructure Domain")
    print("  Lár Execution Spine — Domain-Agnostic Routing")
    print("=" * 60)
    print(f"\n  Monitoring probes  : {N_PROBES}")
    print(f"  Network nodes      : {N_NODES}")
    print(f"  Load latent dim    : {LOAD_DIM}")
    print(f"  Topology latent dim: {TOPOLOGY_DIM}")

    load_data, topo_data = get_mock_network_input(n_snapshots=4)
    print(f"\n  load_data shape    : {list(load_data.shape)}   (snapshots × probes × features)")
    print(f"  topo_data shape    : {list(topo_data.shape)}   (1 × nodes × features)")

    entry_node = build_infrastructure_graph()
    executor   = GraphExecutor(log_dir="infrastructure_logs", hmac_secret="snath_ai_infrastructure_eu_compliance_2026")

    all_reports = []
    for snapshot_idx in range(load_data.shape[0]):
        print(f"\n{'─' * 60}")
        print(f"  Processing telemetry snapshot {snapshot_idx + 1}/{load_data.shape[0]}")
        print(f"{'─' * 60}")

        initial_state = {
            "load_data":      load_data[snapshot_idx].unsqueeze(0),  # (1, N_PROBES, 6)
            "topo_data":      topo_data,                              # (1, N_NODES, 6)
            "snapshot_index": snapshot_idx,
        }

        for step in executor.run_step_by_step(entry_node, initial_state, max_steps=20):
            pass

        report = initial_state.get("incident_report", {})
        all_reports.append(report)

    print("\n" + "=" * 60)
    print("  INFRASTRUCTURE-JEPA SUMMARY")
    print("=" * 60)
    for i, r in enumerate(all_reports):
        tier = r.get("risk_tier", "UNKNOWN")
        prob = r.get("failure_prob", 0.0)
        print(f"  Snapshot {i}: prob={prob:.4f}  tier={tier}")

    print("\n  Domain Isomorphism Validated:")
    print("    Materials domain      → electrochemical state × crystal lattice")
    print("    Seismic domain        → crustal stress field × fault topology")
    print("    Infrastructure domain → network load state × server topology")
    print("  Identical mathematical pipeline. Zero domain-specific code")
    print("  in the Lár routing spine. Same CrossAttention → topk extraction.")
    print("=" * 60)


if __name__ == "__main__":
    main()
